/*
 * \file opamp.c
 *
 * \brief OPAMP used to configure the OPAMPs.
 *
 *  (c) 2020 Microchip Technology Inc. and its subsidiaries.
 *
 *  Subject to your compliance with these terms,you may use this software and
 *  any derivatives exclusively with Microchip products.It is your responsibility
 *  to comply with third party license terms applicable to your use of third party
 *  software (including open source software) that may accompany Microchip software.
 *
 *  THIS SOFTWARE IS SUPPLIED BY MICROCHIP "AS IS". NO WARRANTIES, WHETHER
 *  EXPRESS, IMPLIED OR STATUTORY, APPLY TO THIS SOFTWARE, INCLUDING ANY IMPLIED
 *  WARRANTIES OF NON-INFRINGEMENT, MERCHANTABILITY, AND FITNESS FOR A
 *  PARTICULAR PURPOSE.
 *
 *  IN NO EVENT WILL MICROCHIP BE LIABLE FOR ANY INDIRECT, SPECIAL, PUNITIVE,
 *  INCIDENTAL OR CONSEQUENTIAL LOSS, DAMAGE, COST OR EXPENSE OF ANY KIND
 *  WHATSOEVER RELATED TO THE SOFTWARE, HOWEVER CAUSED, EVEN IF MICROCHIP HAS
 *  BEEN ADVISED OF THE POSSIBILITY OR THE DAMAGES ARE FORESEEABLE. TO THE
 *  FULLEST EXTENT ALLOWED BY LAW, MICROCHIP'S TOTAL LIABILITY ON ALL CLAIMS IN
 *  ANY WAY RELATED TO THIS SOFTWARE WILL NOT EXCEED THE AMOUNT OF FEES, IF ANY,
 *  THAT YOU HAVE PAID DIRECTLY TO MICROCHIP FOR THIS SOFTWARE.
 */

/*
Refer to the table below to find what MUXWIP setting gives what wiper position.
  +-----------------------+-----+-----+
  |     MUXWIP setting    | R1  | R2  |
  +-----------------------+-----+-----+
  |  OPAMP_MUXWIP_WIP0_gc | 15R |  1R |
  |  OPAMP_MUXWIP_WIP1_gc | 14R |  2R |
  |  OPAMP_MUXWIP_WIP2_gc | 12R |  4R |
  |  OPAMP_MUXWIP_WIP3_gc |  8R |  8R |
  |  OPAMP_MUXWIP_WIP4_gc |  6R | 10R |
  |  OPAMP_MUXWIP_WIP5_gc |  4R | 12R |
  |  OPAMP_MUXWIP_WIP6_gc |  2R | 14R |
  |  OPAMP_MUXWIP_WIP7_gc |  1R | 15R |
  +-----------------------+-----+-----+
*/

#include "opamp.h"

void opamp_init(void){
	OPAMP.TIMEBASE = ceil(F_CPU*0.000001)-1;
	
	/*Initialize OP0 */
	OPAMP.OP0CTRLA = OPAMP_OP0CTRLA_OUTMODE_NORMAL_gc | OPAMP_ALWAYSON_bm | OPAMP_RUNSTBY_bm;
	OPAMP.OP0SETTLE = OPAMP_MAX_SETTLE_TIME;

	/*Initialize OP1*/
	OPAMP.OP1CTRLA = OPAMP_OP1CTRLA_OUTMODE_NORMAL_gc | OPAMP_ALWAYSON_bm | OPAMP_RUNSTBY_bm;
	OPAMP.OP1SETTLE = OPAMP_MAX_SETTLE_TIME;

	/*Initialize OP2*/
	OPAMP.OP2CTRLA = OPAMP_OP2CTRLA_OUTMODE_NORMAL_gc | OPAMP_ALWAYSON_bm | OPAMP_RUNSTBY_bm;
	OPAMP.OP2SETTLE = OPAMP_MAX_SETTLE_TIME;

	OPAMP.CTRLA = OPAMP_ENABLE_bm;
}

void opamp_single_config(void){

	/*OP0 connected directly to pins*/
	OPAMP.OP0RESMUX = OPAMP_OP0RESMUX_MUXWIP_WIP0_gc | OPAMP_OP0RESMUX_MUXBOT_OFF_gc | OPAMP_OP0RESMUX_MUXTOP_OFF_gc;
	OPAMP.OP0INMUX = OPAMP_OP0INMUX_MUXNEG_INN_gc | OPAMP_OP0INMUX_MUXPOS_INP_gc;

	/*OP1 connected directly to pins*/
	OPAMP.OP1RESMUX = OPAMP_OP1RESMUX_MUXWIP_WIP0_gc | OPAMP_OP1RESMUX_MUXBOT_OFF_gc | OPAMP_OP1RESMUX_MUXTOP_OFF_gc;
	OPAMP.OP1INMUX = OPAMP_OP1INMUX_MUXNEG_INN_gc | OPAMP_OP1INMUX_MUXPOS_INP_gc;

	/*OP2 connected directly to pins*/
	OPAMP.OP2RESMUX = OPAMP_OP2RESMUX_MUXWIP_WIP0_gc | OPAMP_OP2RESMUX_MUXBOT_OFF_gc | OPAMP_OP2RESMUX_MUXTOP_OFF_gc;
	OPAMP.OP2INMUX = OPAMP_OP2INMUX_MUXNEG_INN_gc | OPAMP_OP2INMUX_MUXPOS_INP_gc;
}

void opamp_voltage_follower_config(void){

	/*OP0 configured as a voltage follower*/
	OPAMP.OP0RESMUX = OPAMP_OP0RESMUX_MUXWIP_WIP0_gc | OPAMP_OP0RESMUX_MUXBOT_OFF_gc | OPAMP_OP0RESMUX_MUXTOP_OFF_gc;
	OPAMP.OP0INMUX = OPAMP_OP0INMUX_MUXNEG_OUT_gc | OPAMP_OP0INMUX_MUXPOS_INP_gc;

	/*OP1 configured as a voltage follower*/
	OPAMP.OP1RESMUX = OPAMP_OP1RESMUX_MUXWIP_WIP0_gc | OPAMP_OP1RESMUX_MUXBOT_OFF_gc | OPAMP_OP1RESMUX_MUXTOP_OFF_gc;
	OPAMP.OP1INMUX = OPAMP_OP1INMUX_MUXNEG_OUT_gc | OPAMP_OP1INMUX_MUXPOS_INP_gc;

	/*OP2 configured as a voltage follower*/
	OPAMP.OP2RESMUX = OPAMP_OP2RESMUX_MUXWIP_WIP0_gc | OPAMP_OP2RESMUX_MUXBOT_OFF_gc | OPAMP_OP2RESMUX_MUXTOP_OFF_gc;
	OPAMP.OP2INMUX = OPAMP_OP2INMUX_MUXNEG_OUT_gc | OPAMP_OP2INMUX_MUXPOS_INP_gc;
}

void opamp_non_inverting_pga_config(void){
	/*OP0 configured as a non inverting pga, gain = 4x*/
	OPAMP.OP0RESMUX = OPAMP_OP0RESMUX_MUXWIP_WIP5_gc | OPAMP_OP0RESMUX_MUXBOT_GND_gc | OPAMP_OP0RESMUX_MUXTOP_OUT_gc;
	OPAMP.OP0INMUX = OPAMP_OP0INMUX_MUXNEG_WIP_gc | OPAMP_OP0INMUX_MUXPOS_INP_gc;

	/*OP1 configured as a non inverting pga, gain = 8x**/
	OPAMP.OP1RESMUX = OPAMP_OP1RESMUX_MUXWIP_WIP6_gc | OPAMP_OP1RESMUX_MUXBOT_GND_gc | OPAMP_OP1RESMUX_MUXTOP_OUT_gc;
	OPAMP.OP1INMUX = OPAMP_OP1INMUX_MUXNEG_WIP_gc | OPAMP_OP1INMUX_MUXPOS_INP_gc;

	/*OP2 configured as a non inverting pga, gain = 16x**/
	OPAMP.OP2RESMUX = OPAMP_OP2RESMUX_MUXWIP_WIP7_gc | OPAMP_OP2RESMUX_MUXBOT_GND_gc | OPAMP_OP2RESMUX_MUXTOP_OUT_gc;
	OPAMP.OP2INMUX = OPAMP_OP2INMUX_MUXNEG_WIP_gc | OPAMP_OP2INMUX_MUXPOS_INP_gc;
}

void opamp_inverting_pga_config(void){
	/*OP0 configured as a inverting pga, gain = -3x*/
	OPAMP.OP0RESMUX = OPAMP_OP0RESMUX_MUXWIP_WIP5_gc | OPAMP_OP0RESMUX_MUXBOT_INN_gc | OPAMP_OP0RESMUX_MUXTOP_OUT_gc;
	OPAMP.OP0INMUX = OPAMP_OP0INMUX_MUXNEG_WIP_gc | OPAMP_OP0INMUX_MUXPOS_VDDDIV2_gc;

	/*OP1 configured as a non inverting pga, gain = -7x*/
	OPAMP.OP1RESMUX = OPAMP_OP1RESMUX_MUXWIP_WIP6_gc | OPAMP_OP1RESMUX_MUXBOT_INN_gc | OPAMP_OP1RESMUX_MUXTOP_OUT_gc;
	OPAMP.OP1INMUX = OPAMP_OP1INMUX_MUXNEG_WIP_gc | OPAMP_OP1INMUX_MUXPOS_VDDDIV2_gc;

	/*OP2 configured as a non inverting pga, gain = -15x*/
	OPAMP.OP2RESMUX = OPAMP_OP2RESMUX_MUXWIP_WIP7_gc | OPAMP_OP2RESMUX_MUXBOT_INN_gc | OPAMP_OP2RESMUX_MUXTOP_OUT_gc;
	OPAMP.OP2INMUX = OPAMP_OP2INMUX_MUXNEG_WIP_gc | OPAMP_OP2INMUX_MUXPOS_VDDDIV2_gc;
}

void opamp_differential_amplifier_config(void){
	/*OP0 configured as part of the differential amplifier, gain = 15x*/
	OPAMP.OP0RESMUX = OPAMP_OP0RESMUX_MUXWIP_WIP0_gc | OPAMP_OP0RESMUX_MUXBOT_OFF_gc | OPAMP_OP0RESMUX_MUXTOP_OFF_gc;
	OPAMP.OP0INMUX = OPAMP_OP0INMUX_MUXNEG_OUT_gc | OPAMP_OP0INMUX_MUXPOS_INP_gc;

	/*OP1 configured as part of the differential amplifier, gain = 15x*/
	OPAMP.OP1RESMUX = OPAMP_OP1RESMUX_MUXWIP_WIP7_gc | OPAMP_OP1RESMUX_MUXBOT_LINKOUT_gc | OPAMP_OP1RESMUX_MUXTOP_OUT_gc;
	OPAMP.OP1INMUX = OPAMP_OP1INMUX_MUXNEG_WIP_gc | OPAMP_OP1INMUX_MUXPOS_INP_gc;

	/*OP2 connected directly to pins*/
	OPAMP.OP2RESMUX = OPAMP_OP2RESMUX_MUXWIP_WIP0_gc | OPAMP_OP2RESMUX_MUXBOT_OFF_gc | OPAMP_OP2RESMUX_MUXTOP_OFF_gc;
	OPAMP.OP2INMUX = OPAMP_OP2INMUX_MUXNEG_INN_gc | OPAMP_OP2INMUX_MUXPOS_INP_gc;
}

void opamp_instrumentation_amplifier_config(void){
	/*OP0 configured as part of the instrumentation amplifier, gain = 15x*/
	OPAMP.OP0RESMUX = OPAMP_OP0RESMUX_MUXWIP_WIP0_gc | OPAMP_OP0RESMUX_MUXBOT_GND_gc | OPAMP_OP0RESMUX_MUXTOP_OUT_gc;
	OPAMP.OP0INMUX = OPAMP_OP0INMUX_MUXNEG_OUT_gc | OPAMP_OP0INMUX_MUXPOS_INP_gc;

	/*OP1 configured as part of the instrumentation amplifier, gain = 15x*/
	OPAMP.OP1RESMUX = OPAMP_OP1RESMUX_MUXWIP_WIP0_gc | OPAMP_OP1RESMUX_MUXBOT_OFF_gc | OPAMP_OP1RESMUX_MUXTOP_OFF_gc;
	OPAMP.OP1INMUX = OPAMP_OP1INMUX_MUXNEG_OUT_gc | OPAMP_OP1INMUX_MUXPOS_INP_gc;

	/*OP2 configured as part of the instrumentation amplifier, gain = 15x*/
	OPAMP.OP2RESMUX = OPAMP_OP2RESMUX_MUXWIP_WIP7_gc | OPAMP_OP2RESMUX_MUXBOT_LINKOUT_gc | OPAMP_OP2RESMUX_MUXTOP_OUT_gc;
	OPAMP.OP2INMUX = OPAMP_OP2INMUX_MUXNEG_WIP_gc | OPAMP_OP2INMUX_MUXPOS_LINKWIP_gc;
}
